-- CreateTable
CREATE TABLE `User` (
    `USER_ID` VARCHAR(191) NOT NULL,
    `EMAIL` VARCHAR(191) NOT NULL,
    `PASSWORD` VARCHAR(191) NOT NULL,
    `ROLE` ENUM('customer', 'personnel') NOT NULL DEFAULT 'customer',

    UNIQUE INDEX `User_EMAIL_key`(`EMAIL`),
    PRIMARY KEY (`USER_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Collect_Coupon` (
    `COLLECT_COUPON_ID` VARCHAR(191) NOT NULL,
    `USER_ID` VARCHAR(191) NOT NULL,
    `COUPON_ID` VARCHAR(191) NOT NULL,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NOT NULL,

    PRIMARY KEY (`COLLECT_COUPON_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Coupon` (
    `COUPON_ID` VARCHAR(191) NOT NULL,
    `COUPON_NAME` VARCHAR(191) NOT NULL,
    `COUPON_DISCOUNT` INTEGER NOT NULL,
    `COUPON_EXPIRED_AT` DATETIME(3) NOT NULL,

    UNIQUE INDEX `Coupon_COUPON_NAME_key`(`COUPON_NAME`),
    PRIMARY KEY (`COUPON_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Reservation` (
    `RESERVATION_ID` VARCHAR(191) NOT NULL,
    `USER_ID` VARCHAR(191) NOT NULL,
    `FLIGHT_ID` VARCHAR(191) NOT NULL,
    `SEAT` INTEGER NOT NULL,
    `COUPON_ID` VARCHAR(191) NULL,
    `TOTAL_PRICE` DOUBLE NOT NULL,
    `FIRST_NAME` VARCHAR(191) NOT NULL,
    `LAST_NAME` VARCHAR(191) NOT NULL,
    `PHONE` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `Reservation_COUPON_ID_key`(`COUPON_ID`),
    PRIMARY KEY (`RESERVATION_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Flight` (
    `FLIGHT_ID` VARCHAR(191) NOT NULL,
    `FLIGHT_NO` VARCHAR(191) NOT NULL,
    `DEPART_DATE` DATETIME(3) NOT NULL,
    `ARRIVE_DATE` DATETIME(3) NOT NULL,
    `DEPART_AIRPORT_ID` VARCHAR(191) NOT NULL,
    `ARRIVE_AIRPORT_ID` VARCHAR(191) NOT NULL,
    `PRICE` DOUBLE NOT NULL,
    `SEAT` INTEGER NOT NULL,
    `PLANE_ID` VARCHAR(191) NOT NULL,
    `AIRLINE_ID` VARCHAR(191) NOT NULL,

    UNIQUE INDEX `Flight_FLIGHT_NO_key`(`FLIGHT_NO`),
    PRIMARY KEY (`FLIGHT_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Airline` (
    `AIRLINE_ID` VARCHAR(191) NOT NULL,
    `OWNER_ID` VARCHAR(191) NOT NULL,
    `NAME_TH` VARCHAR(191) NOT NULL,
    `NAME_EN` VARCHAR(191) NOT NULL,
    `PHONE` VARCHAR(191) NOT NULL,

    UNIQUE INDEX `Airline_OWNER_ID_key`(`OWNER_ID`),
    UNIQUE INDEX `Airline_NAME_TH_key`(`NAME_TH`),
    UNIQUE INDEX `Airline_NAME_EN_key`(`NAME_EN`),
    UNIQUE INDEX `Airline_PHONE_key`(`PHONE`),
    PRIMARY KEY (`AIRLINE_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Plane` (
    `PLANE_ID` VARCHAR(191) NOT NULL,
    `PLANE_NAME` VARCHAR(191) NOT NULL,
    `PLANE_SEAT` INTEGER NOT NULL,
    `airlineId` VARCHAR(191) NULL,

    UNIQUE INDEX `Plane_PLANE_NAME_key`(`PLANE_NAME`),
    PRIMARY KEY (`PLANE_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Airline_In_Airport` (
    `AIRLINE_IN_AIRPORT_ID` VARCHAR(191) NOT NULL,
    `AIRLINE_ID` VARCHAR(191) NOT NULL,
    `AIRPORT_ID` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`AIRLINE_IN_AIRPORT_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Airport` (
    `AIRPORT_ID` VARCHAR(191) NOT NULL,
    `NAME_TH` VARCHAR(191) NOT NULL,
    `NAME_EN` VARCHAR(191) NOT NULL,
    `COUNTRIES_ID` VARCHAR(191) NOT NULL,

    UNIQUE INDEX `Airport_NAME_TH_key`(`NAME_TH`),
    UNIQUE INDEX `Airport_NAME_EN_key`(`NAME_EN`),
    PRIMARY KEY (`AIRPORT_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Countries` (
    `CODE` VARCHAR(191) NOT NULL,
    `NAME_TH` VARCHAR(191) NOT NULL,
    `NAME_EN` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `Countries_NAME_TH_key`(`NAME_TH`),
    UNIQUE INDEX `Countries_NAME_EN_key`(`NAME_EN`),
    PRIMARY KEY (`CODE`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Collect_Coupon` ADD CONSTRAINT `Collect_Coupon_USER_ID_fkey` FOREIGN KEY (`USER_ID`) REFERENCES `User`(`USER_ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Collect_Coupon` ADD CONSTRAINT `Collect_Coupon_COUPON_ID_fkey` FOREIGN KEY (`COUPON_ID`) REFERENCES `Coupon`(`COUPON_ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Reservation` ADD CONSTRAINT `Reservation_USER_ID_fkey` FOREIGN KEY (`USER_ID`) REFERENCES `User`(`USER_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Reservation` ADD CONSTRAINT `Reservation_FLIGHT_ID_fkey` FOREIGN KEY (`FLIGHT_ID`) REFERENCES `Flight`(`FLIGHT_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Reservation` ADD CONSTRAINT `Reservation_COUPON_ID_fkey` FOREIGN KEY (`COUPON_ID`) REFERENCES `Coupon`(`COUPON_ID`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Flight` ADD CONSTRAINT `Flight_PLANE_ID_fkey` FOREIGN KEY (`PLANE_ID`) REFERENCES `Plane`(`PLANE_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Flight` ADD CONSTRAINT `Flight_ARRIVE_AIRPORT_ID_fkey` FOREIGN KEY (`ARRIVE_AIRPORT_ID`) REFERENCES `Airport`(`AIRPORT_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Flight` ADD CONSTRAINT `Flight_DEPART_AIRPORT_ID_fkey` FOREIGN KEY (`DEPART_AIRPORT_ID`) REFERENCES `Airport`(`AIRPORT_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Flight` ADD CONSTRAINT `Flight_AIRLINE_ID_fkey` FOREIGN KEY (`AIRLINE_ID`) REFERENCES `Airline`(`AIRLINE_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Airline` ADD CONSTRAINT `Airline_OWNER_ID_fkey` FOREIGN KEY (`OWNER_ID`) REFERENCES `User`(`USER_ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Plane` ADD CONSTRAINT `Plane_airlineId_fkey` FOREIGN KEY (`airlineId`) REFERENCES `Airline`(`AIRLINE_ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Airline_In_Airport` ADD CONSTRAINT `Airline_In_Airport_AIRLINE_ID_fkey` FOREIGN KEY (`AIRLINE_ID`) REFERENCES `Airline`(`AIRLINE_ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Airline_In_Airport` ADD CONSTRAINT `Airline_In_Airport_AIRPORT_ID_fkey` FOREIGN KEY (`AIRPORT_ID`) REFERENCES `Airport`(`AIRPORT_ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Airport` ADD CONSTRAINT `Airport_COUNTRIES_ID_fkey` FOREIGN KEY (`COUNTRIES_ID`) REFERENCES `Countries`(`CODE`) ON DELETE RESTRICT ON UPDATE CASCADE;
