import Head from 'next/head';
const Meta = ({ title }: { title: string }) => {
  return (
    <Head>
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta name="description" content="Generated by create next app" />
      <meta charSet="utf-8" />
      <link rel="icon" href="/favicon.png" />
      <title>{`${title} - subcription`}</title>
    </Head>
  );
};

export default Meta;
